import type { ThemeConfig, Investment } from "../types";

export const KALSHI_BASE_URL = "https://trading-api.kalshi.com/trade-api/v2";
export const POLYMARKET_GAMMA_URL = "https://gamma-api.polymarket.com";

export const STRONG_SIGNAL_THRESHOLD = 0.75;
export const MODERATE_SIGNAL_THRESHOLD = 0.60;

export const MIN_VOLUME_KALSHI = 1000;
export const MIN_VOLUME_POLYMARKET = 5000;

export const REQUEST_TIMEOUT_MS = 5000;

/** Cap any single theme's contribution to prevent crypto/AI from dominating. */
export const MAX_THEME_WEIGHT = 0.3;

/** Bonus multiplier for recommendations appearing across multiple themes. */
export const DIVERSIFICATION_BONUS = 0.1;

export const SIGNAL_THEMES: Record<string, ThemeConfig> = {
  fed_rate: {
    label: "Fed Interest Rate Decisions",
    keywords: ["fed", "interest rate", "fomc", "federal reserve", "rate cut", "rate hike"],
    kalshi_series: ["FED", "FOMC"],
  },
  inflation: {
    label: "Inflation / CPI",
    keywords: ["inflation", "cpi", "consumer price", "pce", "annual inflation"],
    kalshi_series: ["CPI", "INFL"],
  },
  recession: {
    label: "Recession Probability",
    keywords: ["recession", "gdp", "economic contraction", "nber", "economic growth", "gdp growth"],
    kalshi_series: ["RECESSION", "GDP"],
  },
  tariffs_trade: {
    label: "Tariffs & Trade Policy",
    keywords: ["tariff", "trade war", "import duty", "trade policy", "trade deal"],
    kalshi_series: [],
  },
  tech_regulation: {
    label: "Tech Regulation & Antitrust",
    keywords: ["antitrust", "tech regulation", "big tech", "breakup", "ftc"],
    kalshi_series: [],
  },
  crypto: {
    label: "Crypto & Digital Assets",
    keywords: ["bitcoin", "crypto", "ethereum", "btc", "digital asset", "stablecoin"],
    kalshi_series: ["BTC", "ETH"],
  },
  energy_climate: {
    label: "Energy & Climate Policy",
    keywords: ["oil price", "energy", "climate", "renewable", "ev mandate", "drilling", "crude oil", "natural gas", "opec", "oil production", "oil (cl)", "brent crude"],
    kalshi_series: [],
  },
  geopolitical: {
    label: "Geopolitical Risk",
    keywords: ["\\bwar\\b", "\\bconflict\\b", "sanctions", "\\bnato\\b", "\\bchina\\b", "taiwan", "russia", "ukraine", "\\biran\\b", "\\bstrike\\b", "ceasefire", "\\bregime\\b", "invasion", "\\bmilitary\\b", "\\btroops\\b", "forces enter"],
    kalshi_series: [],
  },
  ai_tech: {
    label: "AI & Technology",
    keywords: ["artificial intelligence", "\\bai\\b", "openai", "\\bgpu\\b", "nvidia", "chatgpt", "\\bagi\\b", "nvda", "anthropic", "databricks", "perplexity"],
    kalshi_series: [],
  },
  housing: {
    label: "Housing Market",
    keywords: ["housing", "home price", "mortgage", "real estate", "home sales"],
    kalshi_series: [],
  },
  employment: {
    label: "Jobs & Employment",
    keywords: ["jobs", "unemployment", "nonfarm", "payroll", "labor", "employment", "jobless claims", "jobs report", "job growth", "us unemployment"],
    kalshi_series: ["JOBS", "UNRATE"],
  },
  government_shutdown: {
    label: "Government Shutdown / Debt Ceiling",
    keywords: ["shutdown", "debt ceiling", "government funding", "dhs shutdown"],
    kalshi_series: [],
  },
  healthcare_biotech: {
    label: "Healthcare & Biotech",
    keywords: ["drug approval", "fda", "medicare", "biotech", "pharmaceutical", "vaccine", "clinical trial", "medicaid"],
    kalshi_series: [],
  },
  financials_banking: {
    label: "Financials & Banking",
    keywords: ["bank regulation", "fdic", "fintech", "credit", "banking crisis", "bank failure", "dodd-frank", "basel", "sofi"],
    kalshi_series: [],
  },
  commodities_agriculture: {
    label: "Commodities & Agriculture",
    keywords: ["gold price", "gold (gc)", "silver (si)", "wheat", "crop", "commodity", "corn", "soybean", "copper", "mining"],
    kalshi_series: [],
  },
  defense_aerospace: {
    label: "Defense & Aerospace",
    keywords: ["defense spending", "military", "nato budget", "space", "pentagon", "arms deal", "missile", "drone"],
    kalshi_series: [],
  },
  consumer_retail: {
    label: "Consumer & Retail",
    keywords: ["consumer spending", "retail sales", "consumer confidence", "holiday spending", "e-commerce", "consumer sentiment"],
    kalshi_series: [],
  },
  stock_market: {
    label: "Stock Market & Indices",
    keywords: ["s&p 500", "s&p500", "sp500", "spy", "spx", "nasdaq 100", "ndx", "dow jones", "djia", "stock market", "russell 2000", "market crash", "bear market", "bull market", "equity market", "stock index", "all time high", "largest company", "market cap"],
    kalshi_series: ["INX", "NASDAQ", "SPY"],
  },
  treasury_bonds: {
    label: "Treasury & Bond Yields",
    keywords: ["treasury yield", "10-year yield", "bond yield", "treasury bond", "2-year yield", "yield curve", "10 year treasury", "30-year bond", "t-bill", "treasury rate", "10-year treasury"],
    kalshi_series: [],
  },
  dollar_forex: {
    label: "US Dollar & Forex",
    keywords: ["us dollar", "dollar index", "dxy", "forex", "euro dollar", "eur/usd", "usd/jpy", "currency", "dollar strength", "dollar weakness", "exchange rate", "bank of japan", "bank of england"],
    kalshi_series: [],
  },
  volatility: {
    label: "Market Volatility",
    keywords: ["vix", "volatility index", "fear index"],
    kalshi_series: [],
  },
};

export const THEME_INVESTMENTS: Record<string, Record<string, Investment[]>> = {
  fed_rate: {
    rate_cut_bullish: [
      { ticker: "TLT", name: "iShares 20+ Year Treasury Bond ETF", direction: "positive", weight: 0.9 },
      { ticker: "SCHD", name: "Schwab US Dividend Equity ETF", direction: "positive", weight: 0.6 },
      { ticker: "XLU", name: "Utilities Select Sector SPDR", direction: "positive", weight: 0.7 },
      { ticker: "VNQ", name: "Vanguard Real Estate ETF", direction: "positive", weight: 0.7 },
      { ticker: "QQQ", name: "Invesco QQQ Trust", direction: "positive", weight: 0.5 },
      { ticker: "VIG", name: "Vanguard Dividend Appreciation ETF", direction: "positive", weight: 0.6 },
      { ticker: "DVY", name: "iShares Dow Jones Select Dividend ETF", direction: "positive", weight: 0.6 },
      { ticker: "QQQJ", name: "Invesco NASDAQ Next Gen 100 ETF", direction: "positive", weight: 0.5 },
      { ticker: "GPMT", name: "Granite Point Mortgage Trust", direction: "positive", weight: 0.7, type: "stock" },
    ],
    rate_hike_bullish: [
      { ticker: "SHV", name: "iShares Short Treasury Bond ETF", direction: "positive", weight: 0.7 },
      { ticker: "KRE", name: "SPDR S&P Regional Banking ETF", direction: "positive", weight: 0.6 },
      { ticker: "NDAQ", name: "Nasdaq Inc", direction: "positive", weight: 0.4, type: "stock" },
      { ticker: "VIG", name: "Vanguard Dividend Appreciation ETF", direction: "negative", weight: 0.4 },
      { ticker: "VNQ", name: "Vanguard Real Estate ETF", direction: "negative", weight: 0.6 },
      { ticker: "GPMT", name: "Granite Point Mortgage Trust", direction: "negative", weight: 0.7, type: "stock" },
    ],
  },
  inflation: {
    high_inflation: [
      { ticker: "TIP", name: "iShares TIPS Bond ETF", direction: "positive", weight: 0.9 },
      { ticker: "GLD", name: "SPDR Gold Shares", direction: "positive", weight: 0.8 },
      { ticker: "DBC", name: "Invesco DB Commodity Index", direction: "positive", weight: 0.7 },
      { ticker: "XLE", name: "Energy Select Sector SPDR", direction: "positive", weight: 0.5 },
      { ticker: "TLT", name: "iShares 20+ Year Treasury Bond ETF", direction: "negative", weight: 0.7 },
      { ticker: "WMT", name: "Walmart", direction: "positive", weight: 0.4, type: "stock" },
      { ticker: "MMM", name: "3M", direction: "negative", weight: 0.3, type: "stock" },
    ],
    low_inflation: [
      { ticker: "TLT", name: "iShares 20+ Year Treasury Bond ETF", direction: "positive", weight: 0.7 },
      { ticker: "QQQ", name: "Invesco QQQ Trust", direction: "positive", weight: 0.5 },
      { ticker: "VOO", name: "Vanguard S&P 500 ETF", direction: "positive", weight: 0.5 },
      { ticker: "VIG", name: "Vanguard Dividend Appreciation ETF", direction: "positive", weight: 0.4 },
      { ticker: "GLD", name: "SPDR Gold Shares", direction: "negative", weight: 0.5 },
    ],
  },
  recession: {
    recession_likely: [
      { ticker: "TLT", name: "iShares 20+ Year Treasury Bond ETF", direction: "positive", weight: 0.8 },
      { ticker: "GLD", name: "SPDR Gold Shares", direction: "positive", weight: 0.7 },
      { ticker: "XLP", name: "Consumer Staples Select Sector SPDR", direction: "positive", weight: 0.7 },
      { ticker: "XLV", name: "Health Care Select Sector SPDR", direction: "positive", weight: 0.6 },
      { ticker: "SPY", name: "SPDR S&P 500 ETF Trust", direction: "negative", weight: 0.8 },
      { ticker: "XLY", name: "Consumer Discretionary Select Sector SPDR", direction: "negative", weight: 0.7 },
      { ticker: "IWM", name: "iShares Russell 2000 ETF", direction: "negative", weight: 0.8 },
      { ticker: "WMT", name: "Walmart", direction: "positive", weight: 0.5, type: "stock" },
      { ticker: "AWAY", name: "Amplify Travel Tech ETF", direction: "negative", weight: 0.7 },
      { ticker: "PEJ", name: "Invesco Leisure and Entertainment ETF", direction: "negative", weight: 0.7 },
      { ticker: "BEDZ", name: "AdvisorShares Hotel ETF", direction: "negative", weight: 0.7 },
      { ticker: "DIS", name: "Disney", direction: "negative", weight: 0.5, type: "stock" },
      { ticker: "SHOP", name: "Shopify", direction: "negative", weight: 0.5, type: "stock" },
    ],
    recession_unlikely: [
      { ticker: "SPY", name: "SPDR S&P 500 ETF Trust", direction: "positive", weight: 0.6 },
      { ticker: "IWM", name: "iShares Russell 2000 ETF", direction: "positive", weight: 0.6 },
      { ticker: "XLY", name: "Consumer Discretionary Select Sector SPDR", direction: "positive", weight: 0.5 },
      { ticker: "VOO", name: "Vanguard S&P 500 ETF", direction: "positive", weight: 0.5 },
      { ticker: "AWAY", name: "Amplify Travel Tech ETF", direction: "positive", weight: 0.5 },
      { ticker: "PEJ", name: "Invesco Leisure and Entertainment ETF", direction: "positive", weight: 0.5 },
      { ticker: "BEDZ", name: "AdvisorShares Hotel ETF", direction: "positive", weight: 0.5 },
      { ticker: "PEVC", name: "Pacer PE/VC ETF", direction: "positive", weight: 0.5 },
      { ticker: "SHOP", name: "Shopify", direction: "positive", weight: 0.4, type: "stock" },
    ],
  },
  tariffs_trade: {
    tariffs_increase: [
      { ticker: "SPY", name: "SPDR S&P 500 ETF Trust", direction: "negative", weight: 0.5 },
      { ticker: "EEM", name: "iShares MSCI Emerging Markets ETF", direction: "negative", weight: 0.8 },
      { ticker: "FXI", name: "iShares China Large-Cap ETF", direction: "negative", weight: 0.9 },
      { ticker: "XLI", name: "Industrial Select Sector SPDR", direction: "negative", weight: 0.6 },
      { ticker: "GLD", name: "SPDR Gold Shares", direction: "positive", weight: 0.5 },
      { ticker: "DBA", name: "Invesco DB Agriculture Fund", direction: "negative", weight: 0.5 },
      { ticker: "TSM", name: "Taiwan Semiconductor Manufacturing", direction: "negative", weight: 0.7, type: "stock" },
      { ticker: "VEA", name: "Vanguard FTSE Developed Markets ETF", direction: "negative", weight: 0.6 },
      { ticker: "SHOP", name: "Shopify", direction: "negative", weight: 0.4, type: "stock" },
      { ticker: "XTN", name: "SPDR S&P Transportation ETF", direction: "negative", weight: 0.5 },
      { ticker: "MMM", name: "3M", direction: "negative", weight: 0.4, type: "stock" },
    ],
    tariffs_decrease: [
      { ticker: "EEM", name: "iShares MSCI Emerging Markets ETF", direction: "positive", weight: 0.7 },
      { ticker: "VEA", name: "Vanguard FTSE Developed Markets ETF", direction: "positive", weight: 0.6 },
      { ticker: "TSM", name: "Taiwan Semiconductor Manufacturing", direction: "positive", weight: 0.6, type: "stock" },
      { ticker: "XLI", name: "Industrial Select Sector SPDR", direction: "positive", weight: 0.5 },
      { ticker: "SHOP", name: "Shopify", direction: "positive", weight: 0.4, type: "stock" },
      { ticker: "XTN", name: "SPDR S&P Transportation ETF", direction: "positive", weight: 0.5 },
    ],
  },
  tech_regulation: {
    regulation_increases: [
      { ticker: "QQQ", name: "Invesco QQQ Trust", direction: "negative", weight: 0.7 },
      { ticker: "META", name: "Meta Platforms", direction: "negative", weight: 0.8, type: "stock" },
      { ticker: "GOOGL", name: "Alphabet", direction: "negative", weight: 0.8, type: "stock" },
      { ticker: "AMZN", name: "Amazon", direction: "negative", weight: 0.6, type: "stock" },
      { ticker: "AAPL", name: "Apple", direction: "negative", weight: 0.6, type: "stock" },
      { ticker: "RSP", name: "Invesco S&P 500 Equal Weight ETF", direction: "positive", weight: 0.4 },
      { ticker: "SNAP", name: "Snap", direction: "negative", weight: 0.5, type: "stock" },
      { ticker: "PINS", name: "Pinterest", direction: "negative", weight: 0.5, type: "stock" },
      { ticker: "NXDR", name: "Nextdoor", direction: "negative", weight: 0.4, type: "stock" },
      { ticker: "FDN", name: "First Trust Dow Jones Internet Index Fund", direction: "negative", weight: 0.6 },
    ],
    regulation_eases: [
      { ticker: "QQQ", name: "Invesco QQQ Trust", direction: "positive", weight: 0.5 },
      { ticker: "META", name: "Meta Platforms", direction: "positive", weight: 0.6, type: "stock" },
      { ticker: "GOOGL", name: "Alphabet", direction: "positive", weight: 0.6, type: "stock" },
      { ticker: "FDN", name: "First Trust Dow Jones Internet Index Fund", direction: "positive", weight: 0.5 },
      { ticker: "IGV", name: "iShares Expanded Tech-Software Sector ETF", direction: "positive", weight: 0.5 },
    ],
  },
  crypto: {
    crypto_bullish: [
      { ticker: "IBIT", name: "iShares Bitcoin Trust ETF", direction: "positive", weight: 0.9 },
      { ticker: "ETHA", name: "iShares Ethereum Trust ETF", direction: "positive", weight: 0.8 },
      { ticker: "COIN", name: "Coinbase Global", direction: "positive", weight: 0.7, type: "stock" },
      { ticker: "MSTR", name: "Strategy (MicroStrategy)", direction: "positive", weight: 0.6, type: "stock" },
      { ticker: "MARA", name: "MARA Holdings", direction: "positive", weight: 0.5, type: "stock" },
    ],
    crypto_bearish: [
      { ticker: "IBIT", name: "iShares Bitcoin Trust ETF", direction: "negative", weight: 0.7 },
      { ticker: "COIN", name: "Coinbase Global", direction: "negative", weight: 0.6, type: "stock" },
      { ticker: "MSTR", name: "Strategy (MicroStrategy)", direction: "negative", weight: 0.5, type: "stock" },
    ],
  },
  energy_climate: {
    fossil_fuel_bullish: [
      { ticker: "XLE", name: "Energy Select Sector SPDR", direction: "positive", weight: 0.9 },
      { ticker: "XOP", name: "SPDR S&P Oil & Gas Exploration ETF", direction: "positive", weight: 0.8 },
      { ticker: "USO", name: "United States Oil Fund", direction: "positive", weight: 0.7 },
      { ticker: "ICLN", name: "iShares Global Clean Energy ETF", direction: "negative", weight: 0.4 },
      { ticker: "SOLR", name: "Guinness Atkinson Sustainable Energy ETF", direction: "negative", weight: 0.4 },
    ],
    renewables_bullish: [
      { ticker: "ICLN", name: "iShares Global Clean Energy ETF", direction: "positive", weight: 0.9 },
      { ticker: "TAN", name: "Invesco Solar ETF", direction: "positive", weight: 0.7 },
      { ticker: "LIT", name: "Global X Lithium & Battery Tech ETF", direction: "positive", weight: 0.6 },
      { ticker: "TSLA", name: "Tesla", direction: "positive", weight: 0.5, type: "stock" },
      { ticker: "SOLR", name: "Guinness Atkinson Sustainable Energy ETF", direction: "positive", weight: 0.8 },
      { ticker: "ESGV", name: "Vanguard ESG U.S. Stock ETF", direction: "positive", weight: 0.5 },
      { ticker: "USSG", name: "Xtrackers MSCI USA Selection Equity ETF", direction: "positive", weight: 0.5 },
      { ticker: "DSI", name: "iShares ESG MSCI KLD 400 ETF", direction: "positive", weight: 0.5 },
      { ticker: "SUSA", name: "iShares ESG Optimized MSCI USA ETF", direction: "positive", weight: 0.5 },
    ],
  },
  geopolitical: {
    risk_elevated: [
      { ticker: "GLD", name: "SPDR Gold Shares", direction: "positive", weight: 0.9 },
      { ticker: "TLT", name: "iShares 20+ Year Treasury Bond ETF", direction: "positive", weight: 0.6 },
      { ticker: "XAR", name: "SPDR S&P Aerospace & Defense ETF", direction: "positive", weight: 0.7 },
      { ticker: "LMT", name: "Lockheed Martin", direction: "positive", weight: 0.6, type: "stock" },
      { ticker: "EEM", name: "iShares MSCI Emerging Markets ETF", direction: "negative", weight: 0.7 },
      { ticker: "SPY", name: "SPDR S&P 500 ETF Trust", direction: "negative", weight: 0.3 },
      { ticker: "TSM", name: "Taiwan Semiconductor Manufacturing", direction: "negative", weight: 0.6, type: "stock" },
      { ticker: "VEA", name: "Vanguard FTSE Developed Markets ETF", direction: "negative", weight: 0.5 },
      { ticker: "AWAY", name: "Amplify Travel Tech ETF", direction: "negative", weight: 0.5 },
      { ticker: "BEDZ", name: "AdvisorShares Hotel ETF", direction: "negative", weight: 0.5 },
    ],
    risk_decline: [
      { ticker: "EEM", name: "iShares MSCI Emerging Markets ETF", direction: "positive", weight: 0.6 },
      { ticker: "SPY", name: "SPDR S&P 500 ETF Trust", direction: "positive", weight: 0.3 },
      { ticker: "GLD", name: "SPDR Gold Shares", direction: "negative", weight: 0.4 },
      { ticker: "VEA", name: "Vanguard FTSE Developed Markets ETF", direction: "positive", weight: 0.5 },
      { ticker: "TSM", name: "Taiwan Semiconductor Manufacturing", direction: "positive", weight: 0.5, type: "stock" },
      { ticker: "AWAY", name: "Amplify Travel Tech ETF", direction: "positive", weight: 0.4 },
      { ticker: "BEDZ", name: "AdvisorShares Hotel ETF", direction: "positive", weight: 0.4 },
    ],
  },
  ai_tech: {
    ai_growth: [
      { ticker: "SMH", name: "VanEck Semiconductor ETF", direction: "positive", weight: 0.9 },
      { ticker: "NVDA", name: "NVIDIA", direction: "positive", weight: 0.9, type: "stock" },
      { ticker: "QQQ", name: "Invesco QQQ Trust", direction: "positive", weight: 0.6 },
      { ticker: "MSFT", name: "Microsoft", direction: "positive", weight: 0.7, type: "stock" },
      { ticker: "GOOGL", name: "Alphabet", direction: "positive", weight: 0.6, type: "stock" },
      { ticker: "BOTZ", name: "Global X Robotics & AI ETF", direction: "positive", weight: 0.7 },
      { ticker: "ROBO", name: "Robo Global Robotics and Automation ETF", direction: "positive", weight: 0.7 },
      { ticker: "ARKQ", name: "ARK Autonomous Technology & Robotics", direction: "positive", weight: 0.6 },
      { ticker: "TSM", name: "Taiwan Semiconductor Manufacturing", direction: "positive", weight: 0.7, type: "stock" },
      { ticker: "NOW", name: "ServiceNow", direction: "positive", weight: 0.6, type: "stock" },
      { ticker: "CRM", name: "Salesforce", direction: "positive", weight: 0.5, type: "stock" },
      { ticker: "DDOG", name: "Datadog", direction: "positive", weight: 0.6, type: "stock" },
      { ticker: "DTCR", name: "Global X Data Center & Digital Infrastructure ETF", direction: "positive", weight: 0.7 },
      { ticker: "WCLD", name: "WisdomTree Cloud Computing Fund", direction: "positive", weight: 0.6 },
      { ticker: "IGV", name: "iShares Expanded Tech-Software Sector ETF", direction: "positive", weight: 0.6 },
      { ticker: "QQQJ", name: "Invesco NASDAQ Next Gen 100 ETF", direction: "positive", weight: 0.5 },
      { ticker: "META", name: "Meta Platforms", direction: "positive", weight: 0.5, type: "stock" },
      { ticker: "HUBS", name: "HubSpot", direction: "positive", weight: 0.5, type: "stock" },
      { ticker: "TRFK", name: "Pacer Data and Digital Revolution ETF", direction: "positive", weight: 0.5 },
    ],
    ai_decline: [
      { ticker: "SMH", name: "VanEck Semiconductor ETF", direction: "negative", weight: 0.6 },
      { ticker: "NVDA", name: "NVIDIA", direction: "negative", weight: 0.6, type: "stock" },
      { ticker: "QQQ", name: "Invesco QQQ Trust", direction: "negative", weight: 0.4 },
      { ticker: "BOTZ", name: "Global X Robotics & AI ETF", direction: "negative", weight: 0.5 },
      { ticker: "ROBO", name: "Robo Global Robotics and Automation ETF", direction: "negative", weight: 0.5 },
      { ticker: "ARKQ", name: "ARK Autonomous Technology & Robotics", direction: "negative", weight: 0.4 },
      { ticker: "DTCR", name: "Global X Data Center & Digital Infrastructure ETF", direction: "negative", weight: 0.5 },
      { ticker: "WCLD", name: "WisdomTree Cloud Computing Fund", direction: "negative", weight: 0.4 },
      { ticker: "TRFK", name: "Pacer Data and Digital Revolution ETF", direction: "negative", weight: 0.4 },
    ],
  },
  housing: {
    housing_downturn: [
      { ticker: "VNQ", name: "Vanguard Real Estate ETF", direction: "negative", weight: 0.8 },
      { ticker: "XHB", name: "SPDR S&P Homebuilders ETF", direction: "negative", weight: 0.9 },
      { ticker: "ITB", name: "iShares US Home Construction ETF", direction: "negative", weight: 0.9 },
      { ticker: "GPMT", name: "Granite Point Mortgage Trust", direction: "negative", weight: 0.7, type: "stock" },
    ],
    housing_strong: [
      { ticker: "VNQ", name: "Vanguard Real Estate ETF", direction: "positive", weight: 0.8 },
      { ticker: "XHB", name: "SPDR S&P Homebuilders ETF", direction: "positive", weight: 0.9 },
      { ticker: "HD", name: "Home Depot", direction: "positive", weight: 0.5, type: "stock" },
      { ticker: "GPMT", name: "Granite Point Mortgage Trust", direction: "positive", weight: 0.6, type: "stock" },
    ],
  },
  employment: {
    strong_jobs: [
      { ticker: "SPY", name: "SPDR S&P 500 ETF Trust", direction: "positive", weight: 0.5 },
      { ticker: "XLY", name: "Consumer Discretionary Select Sector SPDR", direction: "positive", weight: 0.6 },
      { ticker: "IWM", name: "iShares Russell 2000 ETF", direction: "positive", weight: 0.6 },
      { ticker: "TLT", name: "iShares 20+ Year Treasury Bond ETF", direction: "negative", weight: 0.4 },
      { ticker: "PEJ", name: "Invesco Leisure and Entertainment ETF", direction: "positive", weight: 0.5 },
      { ticker: "AWAY", name: "Amplify Travel Tech ETF", direction: "positive", weight: 0.4 },
      { ticker: "BEDZ", name: "AdvisorShares Hotel ETF", direction: "positive", weight: 0.4 },
      { ticker: "TOST", name: "Toast", direction: "positive", weight: 0.4, type: "stock" },
      { ticker: "EB", name: "Eventbrite", direction: "positive", weight: 0.3, type: "stock" },
    ],
    weak_jobs: [
      { ticker: "TLT", name: "iShares 20+ Year Treasury Bond ETF", direction: "positive", weight: 0.6 },
      { ticker: "XLP", name: "Consumer Staples Select Sector SPDR", direction: "positive", weight: 0.5 },
      { ticker: "SPY", name: "SPDR S&P 500 ETF Trust", direction: "negative", weight: 0.4 },
      { ticker: "IWM", name: "iShares Russell 2000 ETF", direction: "negative", weight: 0.5 },
      { ticker: "AWAY", name: "Amplify Travel Tech ETF", direction: "negative", weight: 0.4 },
      { ticker: "PEJ", name: "Invesco Leisure and Entertainment ETF", direction: "negative", weight: 0.4 },
    ],
  },
  government_shutdown: {
    shutdown_likely: [
      { ticker: "SHV", name: "iShares Short Treasury Bond ETF", direction: "positive", weight: 0.5 },
      { ticker: "GLD", name: "SPDR Gold Shares", direction: "positive", weight: 0.4 },
      { ticker: "SPY", name: "SPDR S&P 500 ETF Trust", direction: "negative", weight: 0.4 },
    ],
    shutdown_unlikely: [
      { ticker: "SPY", name: "SPDR S&P 500 ETF Trust", direction: "positive", weight: 0.3 },
      { ticker: "VOO", name: "Vanguard S&P 500 ETF", direction: "positive", weight: 0.3 },
    ],
  },
  healthcare_biotech: {
    biotech_bullish: [
      { ticker: "XBI", name: "SPDR S&P Biotech ETF", direction: "positive", weight: 0.9 },
      { ticker: "IBB", name: "iShares Biotechnology ETF", direction: "positive", weight: 0.8 },
      { ticker: "JNJ", name: "Johnson & Johnson", direction: "positive", weight: 0.5, type: "stock" },
      { ticker: "PFE", name: "Pfizer", direction: "positive", weight: 0.5, type: "stock" },
      { ticker: "XLV", name: "Health Care Select Sector SPDR", direction: "positive", weight: 0.7 },
      { ticker: "ARKG", name: "ARK Genomic Revolution ETF", direction: "positive", weight: 0.7 },
      { ticker: "SOLV", name: "Solventum Corporation", direction: "positive", weight: 0.5, type: "stock" },
    ],
    biotech_bearish: [
      { ticker: "XBI", name: "SPDR S&P Biotech ETF", direction: "negative", weight: 0.7 },
      { ticker: "IBB", name: "iShares Biotechnology ETF", direction: "negative", weight: 0.6 },
      { ticker: "ARKG", name: "ARK Genomic Revolution ETF", direction: "negative", weight: 0.6 },
      { ticker: "XLV", name: "Health Care Select Sector SPDR", direction: "negative", weight: 0.4 },
    ],
  },
  financials_banking: {
    banking_bullish: [
      { ticker: "XLF", name: "Financial Select Sector SPDR", direction: "positive", weight: 0.9 },
      { ticker: "KRE", name: "SPDR S&P Regional Banking ETF", direction: "positive", weight: 0.8 },
      { ticker: "JPM", name: "JPMorgan Chase", direction: "positive", weight: 0.6, type: "stock" },
      { ticker: "GS", name: "Goldman Sachs", direction: "positive", weight: 0.6, type: "stock" },
      { ticker: "NDAQ", name: "Nasdaq Inc", direction: "positive", weight: 0.5, type: "stock" },
      { ticker: "PEVC", name: "Pacer PE/VC ETF", direction: "positive", weight: 0.5 },
    ],
    banking_crisis: [
      { ticker: "XLF", name: "Financial Select Sector SPDR", direction: "negative", weight: 0.9 },
      { ticker: "KRE", name: "SPDR S&P Regional Banking ETF", direction: "negative", weight: 0.9 },
      { ticker: "GLD", name: "SPDR Gold Shares", direction: "positive", weight: 0.5 },
      { ticker: "TLT", name: "iShares 20+ Year Treasury Bond ETF", direction: "positive", weight: 0.6 },
      { ticker: "GPMT", name: "Granite Point Mortgage Trust", direction: "negative", weight: 0.8, type: "stock" },
      { ticker: "NDAQ", name: "Nasdaq Inc", direction: "negative", weight: 0.5, type: "stock" },
    ],
  },
  commodities_agriculture: {
    commodities_bullish: [
      { ticker: "GLD", name: "SPDR Gold Shares", direction: "positive", weight: 0.9 },
      { ticker: "SLV", name: "iShares Silver Trust", direction: "positive", weight: 0.8 },
      { ticker: "DBA", name: "Invesco DB Agriculture Fund", direction: "positive", weight: 0.8 },
      { ticker: "FCX", name: "Freeport-McMoRan", direction: "positive", weight: 0.6, type: "stock" },
      { ticker: "DBC", name: "Invesco DB Commodity Index", direction: "positive", weight: 0.7 },
      { ticker: "MMM", name: "3M", direction: "positive", weight: 0.3, type: "stock" },
    ],
    commodities_bearish: [
      { ticker: "GLD", name: "SPDR Gold Shares", direction: "negative", weight: 0.6 },
      { ticker: "DBC", name: "Invesco DB Commodity Index", direction: "negative", weight: 0.6 },
      { ticker: "DBA", name: "Invesco DB Agriculture Fund", direction: "negative", weight: 0.5 },
    ],
  },
  defense_aerospace: {
    defense_decline: [
      { ticker: "ITA", name: "iShares U.S. Aerospace & Defense ETF", direction: "negative", weight: 0.5 },
      { ticker: "XAR", name: "SPDR S&P Aerospace & Defense ETF", direction: "negative", weight: 0.5 },
    ],
    defense_increase: [
      { ticker: "ITA", name: "iShares U.S. Aerospace & Defense ETF", direction: "positive", weight: 0.9 },
      { ticker: "LMT", name: "Lockheed Martin", direction: "positive", weight: 0.8, type: "stock" },
      { ticker: "RTX", name: "RTX Corporation", direction: "positive", weight: 0.7, type: "stock" },
      { ticker: "BA", name: "Boeing", direction: "positive", weight: 0.5, type: "stock" },
      { ticker: "XAR", name: "SPDR S&P Aerospace & Defense ETF", direction: "positive", weight: 0.8 },
    ],
  },
  consumer_retail: {
    consumer_strong: [
      { ticker: "XRT", name: "SPDR S&P Retail ETF", direction: "positive", weight: 0.9 },
      { ticker: "XLY", name: "Consumer Discretionary Select Sector SPDR", direction: "positive", weight: 0.8 },
      { ticker: "AMZN", name: "Amazon", direction: "positive", weight: 0.6, type: "stock" },
      { ticker: "WMT", name: "Walmart", direction: "positive", weight: 0.5, type: "stock" },
      { ticker: "DIS", name: "Disney", direction: "positive", weight: 0.5, type: "stock" },
      { ticker: "SHOP", name: "Shopify", direction: "positive", weight: 0.5, type: "stock" },
      { ticker: "TOST", name: "Toast", direction: "positive", weight: 0.4, type: "stock" },
      { ticker: "PEJ", name: "Invesco Leisure and Entertainment ETF", direction: "positive", weight: 0.6 },
      { ticker: "AWAY", name: "Amplify Travel Tech ETF", direction: "positive", weight: 0.5 },
      { ticker: "BEDZ", name: "AdvisorShares Hotel ETF", direction: "positive", weight: 0.5 },
      { ticker: "EB", name: "Eventbrite", direction: "positive", weight: 0.4, type: "stock" },
      { ticker: "PINS", name: "Pinterest", direction: "positive", weight: 0.4, type: "stock" },
      { ticker: "SNAP", name: "Snap", direction: "positive", weight: 0.3, type: "stock" },
      { ticker: "NXDR", name: "Nextdoor", direction: "positive", weight: 0.3, type: "stock" },
    ],
    consumer_weak: [
      { ticker: "XRT", name: "SPDR S&P Retail ETF", direction: "negative", weight: 0.8 },
      { ticker: "XLY", name: "Consumer Discretionary Select Sector SPDR", direction: "negative", weight: 0.7 },
      { ticker: "XLP", name: "Consumer Staples Select Sector SPDR", direction: "positive", weight: 0.6 },
      { ticker: "DIS", name: "Disney", direction: "negative", weight: 0.5, type: "stock" },
      { ticker: "SHOP", name: "Shopify", direction: "negative", weight: 0.4, type: "stock" },
      { ticker: "AWAY", name: "Amplify Travel Tech ETF", direction: "negative", weight: 0.5 },
      { ticker: "PEJ", name: "Invesco Leisure and Entertainment ETF", direction: "negative", weight: 0.5 },
      { ticker: "BEDZ", name: "AdvisorShares Hotel ETF", direction: "negative", weight: 0.5 },
      { ticker: "EB", name: "Eventbrite", direction: "negative", weight: 0.4, type: "stock" },
      { ticker: "WMT", name: "Walmart", direction: "positive", weight: 0.4, type: "stock" },
    ],
  },
  stock_market: {
    market_bullish: [
      { ticker: "SPY", name: "SPDR S&P 500 ETF Trust", direction: "positive", weight: 0.9 },
      { ticker: "QQQ", name: "Invesco QQQ Trust", direction: "positive", weight: 0.8 },
      { ticker: "IWM", name: "iShares Russell 2000 ETF", direction: "positive", weight: 0.7 },
      { ticker: "DIA", name: "SPDR Dow Jones Industrial Average ETF", direction: "positive", weight: 0.7 },
      { ticker: "VTI", name: "Vanguard Total Stock Market ETF", direction: "positive", weight: 0.6 },
      { ticker: "VOO", name: "Vanguard S&P 500 ETF", direction: "positive", weight: 0.7 },
      { ticker: "ESGV", name: "Vanguard ESG U.S. Stock ETF", direction: "positive", weight: 0.5 },
      { ticker: "USSG", name: "Xtrackers MSCI USA Selection Equity ETF", direction: "positive", weight: 0.5 },
      { ticker: "DSI", name: "iShares ESG MSCI KLD 400 ETF", direction: "positive", weight: 0.5 },
      { ticker: "SUSA", name: "iShares ESG Optimized MSCI USA ETF", direction: "positive", weight: 0.5 },
      { ticker: "QQQJ", name: "Invesco NASDAQ Next Gen 100 ETF", direction: "positive", weight: 0.6 },
      { ticker: "FDN", name: "First Trust Dow Jones Internet Index Fund", direction: "positive", weight: 0.6 },
      { ticker: "NDAQ", name: "Nasdaq Inc", direction: "positive", weight: 0.5, type: "stock" },
      { ticker: "PEVC", name: "Pacer PE/VC ETF", direction: "positive", weight: 0.4 },
    ],
    market_downturn: [
      { ticker: "SPY", name: "SPDR S&P 500 ETF Trust", direction: "negative", weight: 0.9 },
      { ticker: "QQQ", name: "Invesco QQQ Trust", direction: "negative", weight: 0.8 },
      { ticker: "IWM", name: "iShares Russell 2000 ETF", direction: "negative", weight: 0.9 },
      { ticker: "GLD", name: "SPDR Gold Shares", direction: "positive", weight: 0.6 },
      { ticker: "TLT", name: "iShares 20+ Year Treasury Bond ETF", direction: "positive", weight: 0.5 },
      { ticker: "VXX", name: "iPath Series B S&P 500 VIX Short-Term Futures ETN", direction: "positive", weight: 0.7 },
      { ticker: "VOO", name: "Vanguard S&P 500 ETF", direction: "negative", weight: 0.7 },
      { ticker: "ESGV", name: "Vanguard ESG U.S. Stock ETF", direction: "negative", weight: 0.5 },
      { ticker: "QQQJ", name: "Invesco NASDAQ Next Gen 100 ETF", direction: "negative", weight: 0.5 },
      { ticker: "FDN", name: "First Trust Dow Jones Internet Index Fund", direction: "negative", weight: 0.5 },
      { ticker: "PEVC", name: "Pacer PE/VC ETF", direction: "negative", weight: 0.4 },
    ],
  },
  treasury_bonds: {
    yields_increase: [
      { ticker: "TBT", name: "ProShares UltraShort 20+ Year Treasury", direction: "positive", weight: 0.9 },
      { ticker: "TLT", name: "iShares 20+ Year Treasury Bond ETF", direction: "negative", weight: 0.9 },
      { ticker: "IEF", name: "iShares 7-10 Year Treasury Bond ETF", direction: "negative", weight: 0.7 },
      { ticker: "KRE", name: "SPDR S&P Regional Banking ETF", direction: "positive", weight: 0.5 },
      { ticker: "VNQ", name: "Vanguard Real Estate ETF", direction: "negative", weight: 0.5 },
      { ticker: "GPMT", name: "Granite Point Mortgage Trust", direction: "negative", weight: 0.5, type: "stock" },
    ],
    yields_decrease: [
      { ticker: "TLT", name: "iShares 20+ Year Treasury Bond ETF", direction: "positive", weight: 0.9 },
      { ticker: "IEF", name: "iShares 7-10 Year Treasury Bond ETF", direction: "positive", weight: 0.7 },
      { ticker: "VNQ", name: "Vanguard Real Estate ETF", direction: "positive", weight: 0.5 },
      { ticker: "XLU", name: "Utilities Select Sector SPDR", direction: "positive", weight: 0.5 },
      { ticker: "VIG", name: "Vanguard Dividend Appreciation ETF", direction: "positive", weight: 0.4 },
      { ticker: "DVY", name: "iShares Dow Jones Select Dividend ETF", direction: "positive", weight: 0.4 },
      { ticker: "GPMT", name: "Granite Point Mortgage Trust", direction: "positive", weight: 0.5, type: "stock" },
    ],
  },
  dollar_forex: {
    dollar_strong: [
      { ticker: "UUP", name: "Invesco DB US Dollar Index Bullish Fund", direction: "positive", weight: 0.9 },
      { ticker: "EEM", name: "iShares MSCI Emerging Markets ETF", direction: "negative", weight: 0.7 },
      { ticker: "GLD", name: "SPDR Gold Shares", direction: "negative", weight: 0.5 },
      { ticker: "FXE", name: "Invesco CurrencyShares Euro Trust", direction: "negative", weight: 0.6 },
      { ticker: "VEA", name: "Vanguard FTSE Developed Markets ETF", direction: "negative", weight: 0.5 },
      { ticker: "TSM", name: "Taiwan Semiconductor Manufacturing", direction: "negative", weight: 0.3, type: "stock" },
    ],
    dollar_weak: [
      { ticker: "UUP", name: "Invesco DB US Dollar Index Bullish Fund", direction: "negative", weight: 0.8 },
      { ticker: "EEM", name: "iShares MSCI Emerging Markets ETF", direction: "positive", weight: 0.7 },
      { ticker: "GLD", name: "SPDR Gold Shares", direction: "positive", weight: 0.6 },
      { ticker: "FXE", name: "Invesco CurrencyShares Euro Trust", direction: "positive", weight: 0.6 },
      { ticker: "VEA", name: "Vanguard FTSE Developed Markets ETF", direction: "positive", weight: 0.5 },
      { ticker: "TSM", name: "Taiwan Semiconductor Manufacturing", direction: "positive", weight: 0.3, type: "stock" },
    ],
  },
  volatility: {
    volatility_high: [
      { ticker: "VXX", name: "iPath Series B S&P 500 VIX Short-Term Futures ETN", direction: "positive", weight: 0.9 },
      { ticker: "UVXY", name: "ProShares Ultra VIX Short-Term Futures ETF", direction: "positive", weight: 0.8 },
      { ticker: "SPY", name: "SPDR S&P 500 ETF Trust", direction: "negative", weight: 0.6 },
      { ticker: "QQQ", name: "Invesco QQQ Trust", direction: "negative", weight: 0.6 },
      { ticker: "GLD", name: "SPDR Gold Shares", direction: "positive", weight: 0.5 },
      { ticker: "TLT", name: "iShares 20+ Year Treasury Bond ETF", direction: "positive", weight: 0.4 },
      { ticker: "VOO", name: "Vanguard S&P 500 ETF", direction: "negative", weight: 0.5 },
    ],
    volatility_low: [
      { ticker: "SPY", name: "SPDR S&P 500 ETF Trust", direction: "positive", weight: 0.5 },
      { ticker: "QQQ", name: "Invesco QQQ Trust", direction: "positive", weight: 0.5 },
      { ticker: "VOO", name: "Vanguard S&P 500 ETF", direction: "positive", weight: 0.4 },
      { ticker: "ESGV", name: "Vanguard ESG U.S. Stock ETF", direction: "positive", weight: 0.3 },
    ],
  },
};
