import { useState } from "react";
import type { DipSignal, TradeLogEntry } from "../../types/dip";

interface ExportReportProps {
  signals: DipSignal[];
  tradeLog: TradeLogEntry[];
  lastChecked: string | null;
  email?: string;
}

function generateReport(
  signals: DipSignal[],
  tradeLog: TradeLogEntry[],
  lastChecked: string | null,
  email?: string
): string {
  const now = new Date().toISOString().slice(0, 10);
  const lines: string[] = [];

  lines.push("=== DipWatcher Signal Report ===");
  lines.push(`Report date: ${now}`);
  if (email) lines.push(`Prepared for: ${email}`);
  if (lastChecked) lines.push(`Signals checked: ${new Date(lastChecked).toLocaleString()}`);
  lines.push("");

  const grouped: Record<string, DipSignal[]> = { BUY: [], SELL: [], WATCH: [], HOLD: [] };
  for (const s of signals) {
    grouped[s.action].push(s);
  }

  for (const action of ["BUY", "SELL", "WATCH", "HOLD"] as const) {
    const group = grouped[action];
    if (group.length === 0) continue;
    lines.push(`--- ${action} (${group.length}) ---`);
    for (const s of group) {
      lines.push(`  ${s.ticker}${s.name ? ` (${s.name})` : ""}`);
      lines.push(`    Price: $${s.currentPrice.toFixed(2)} | 30d: ${s.pct30d >= 0 ? "+" : ""}${s.pct30d}% | Cost: ${s.pctFromCost >= 0 ? "+" : ""}${s.pctFromCost}%`);
      lines.push(`    ${s.reason}`);
      lines.push(`    ${s.detail}`);
    }
    lines.push("");
  }

  if (tradeLog.length > 0) {
    const recent = [...tradeLog]
      .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
      .slice(0, 20);
    lines.push(`--- Trade Log (last ${recent.length} of ${tradeLog.length}) ---`);
    for (const t of recent) {
      lines.push(`  ${t.date} ${t.action} ${t.ticker} — ${t.shares} shares @ $${t.price.toFixed(2)} = $${t.amount.toLocaleString()}${t.notes ? ` (${t.notes})` : ""}`);
    }
    lines.push("");
  }

  lines.push("Generated by DipWatcher · market-signals");
  return lines.join("\n");
}

export default function ExportReport({ signals, tradeLog, lastChecked, email }: ExportReportProps) {
  const [copied, setCopied] = useState(false);
  const report = generateReport(signals, tradeLog, lastChecked, email);

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(report);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback: select all text in the pre block
      const pre = document.getElementById("dw-report-text");
      if (pre) {
        const range = document.createRange();
        range.selectNodeContents(pre);
        window.getSelection()?.removeAllRanges();
        window.getSelection()?.addRange(range);
      }
    }
  }

  return (
    <div className="space-y-3">
      <div className="flex justify-between items-center">
        <h3 className="text-sm font-medium text-gray-700 dark:text-gray-300">Signal Report</h3>
        <button onClick={handleCopy} className="px-3 py-1 text-sm bg-indigo-600 text-white rounded hover:bg-indigo-700">
          {copied ? "Copied!" : "Copy to clipboard"}
        </button>
      </div>
      <pre
        id="dw-report-text"
        className="text-xs bg-gray-50 dark:bg-gray-800 border dark:border-gray-700 rounded p-4 overflow-x-auto whitespace-pre-wrap text-gray-700 dark:text-gray-300 max-h-[500px] overflow-y-auto"
      >
        {report}
      </pre>
    </div>
  );
}
